<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="esdl" nsURI="http://www.tno.nl/esdl" nsPrefix="esdl">
  <eClassifiers xsi:type="ecore:EClass" name="EnergyAsset" abstract="true" eSuperTypes="#//Asset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" upperBound="-1" eType="#//Port"
        containment="true" eOpposite="#//Port/energyasset"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Producer" abstract="true" eSuperTypes="#//EnergyAsset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prodType" eType="#//ProdTypeEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Consumer" abstract="true" eSuperTypes="#//EnergyAsset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="consType" eType="#//ConsTypeEnum"
        defaultValueLiteral="PRIMARY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Storage" abstract="true" eSuperTypes="#//EnergyAsset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="efficiency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profile" eType="#//GenericProfile"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conversion" abstract="true" eSuperTypes="#//EnergyAsset">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Conversion Capability"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="efficiency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transport" abstract="true" eSuperTypes="#//EnergyAsset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CommodityEnum">
    <eLiterals name="ELECTRICITY"/>
    <eLiterals name="GAS" value="1"/>
    <eLiterals name="HEAT" value="2"/>
    <eLiterals name="H2" value="3"/>
    <eLiterals name="BIOGAS" value="4"/>
    <eLiterals name="CO2" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnergySystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="geographicalScope" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sector" upperBound="-1"
        eType="#//SectorEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measures" eType="#//Measures"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" upperBound="-1"
        eType="#//Instance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="potentials" eType="#//Potentials"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="energySystemInformation"
        eType="#//EnergySystemInformation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WindTurbine" eSuperTypes="#//Producer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="power" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rotorDiameter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PVPanel" eSuperTypes="#//Producer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="power" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="panelEfficiency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inverterEfficiency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Battery" eSuperTypes="#//Storage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selfDischarge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxChargeDischargeCycli"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chargeEfficiency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dischargeEfficiency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElectricityNetwork" eSuperTypes="#//Transport"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElectricityCable" eSuperTypes="#//Transport"/>
  <eClassifiers xsi:type="ecore:EClass" name="AggregatedConsumer" eSuperTypes="#//Consumer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregationOf" upperBound="-1"
        eType="#//Consumer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuildingUnit" eSuperTypes="#//AbstractBuilding">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//BuildingTypeEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="housingType" eType="#//HousingTypeEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="building" lowerBound="1"
        eType="#//Building" eOpposite="#//Building/buildingUnits"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Area">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scope" eType="#//AreaScopeEnum"
        defaultValueLiteral="UNDEFINED"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//AreaTypeEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="#//Location"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contour" eType="#//Contour"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="socialProperties" eType="#//SocialProperties"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="economicProperties" eType="#//EconomicProperties"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="potentials" upperBound="-1"
        eType="#//Potential" eOpposite="#//Potential/areas"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asset" upperBound="-1"
        eType="#//Asset" containment="true" eOpposite="#//Asset/area"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="area" upperBound="-1" eType="#//Area"
        containment="true" eOpposite="#//Area/containingArea"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containingArea" eType="#//Area"
        eOpposite="#//Area/area"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commodity" eType="#//CommodityEnum"
        defaultValueLiteral="ELECTRICITY"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxPower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="energyasset" lowerBound="1"
        eType="#//EnergyAsset" eOpposite="#//EnergyAsset/port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profile" eType="#//GenericProfile"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregatedProducer" eSuperTypes="#//Producer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregationOf" upperBound="-1"
        eType="#//Producer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AreaScopeEnum">
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="BUILDING" value="1"/>
    <eLiterals name="STREET" value="2"/>
    <eLiterals name="NEIGHBOURHOOD" value="3"/>
    <eLiterals name="DISTRICT" value="4"/>
    <eLiterals name="VILLAGE" value="5"/>
    <eLiterals name="CITY" value="6"/>
    <eLiterals name="MUNICIPALITY" value="7"/>
    <eLiterals name="REGION" value="8"/>
    <eLiterals name="PROVINCE" value="9"/>
    <eLiterals name="STATE" value="10"/>
    <eLiterals name="COUNTRY" value="11"/>
    <eLiterals name="CONTINENT" value="12"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProfileTypeEnum">
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="SOLARIRRADIANCE_IN_W_PER_M2" value="1"/>
    <eLiterals name="WINDSPEED_IN_M_PER_S" value="2"/>
    <eLiterals name="STATEOFCHARGE_IN_WS" value="3"/>
    <eLiterals name="ENERGY_IN_WH" value="4"/>
    <eLiterals name="ENERGY_IN_KWH" value="5"/>
    <eLiterals name="ENERGY_IN_MWH" value="6"/>
    <eLiterals name="ENERGY_IN_GWH" value="7"/>
    <eLiterals name="ENERGY_IN_J" value="8"/>
    <eLiterals name="ENERGY_IN_KJ" value="9"/>
    <eLiterals name="ENERGY_IN_MJ" value="10"/>
    <eLiterals name="ENERGY_IN_GJ" value="11"/>
    <eLiterals name="ENERGY_IN_TJ" value="12"/>
    <eLiterals name="ENERGY_IN_PJ" value="13"/>
    <eLiterals name="TEMPERATURE_IN_C" value="14"/>
    <eLiterals name="TEMPERATURE_IN_K" value="15"/>
    <eLiterals name="POWER_IN_W" value="16"/>
    <eLiterals name="POWER_IN_KW" value="17"/>
    <eLiterals name="POWER_IN_MW" value="18"/>
    <eLiterals name="POWER_IN_GW" value="19"/>
    <eLiterals name="POWER_IN_TW" value="20"/>
    <eLiterals name="MONEY_IN_EUR" value="21"/>
    <eLiterals name="MONEY_IN_KEUR" value="22"/>
    <eLiterals name="MONEY_IN_MEUR" value="23"/>
    <eLiterals name="PERCENTAGE" value="24"/>
    <eLiterals name="MONEY_IN_EUR_PER_KW" value="25"/>
    <eLiterals name="MONEY_IN_EUR_PER_KWH" value="26"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Duration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="durarionUnit" eType="#//DurationUnitEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DurationUnitEnum">
    <eLiterals name="SECOND"/>
    <eLiterals name="MINUTE" value="1"/>
    <eLiterals name="UUR" value="2"/>
    <eLiterals name="DAY" value="3"/>
    <eLiterals name="WEEK" value="4"/>
    <eLiterals name="MONTH" value="5"/>
    <eLiterals name="YEAR" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InPort" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectedToOut" upperBound="-1"
        eType="#//OutPort" eOpposite="#//OutPort/connectedToIn"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutPort" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectedToIn" upperBound="-1"
        eType="#//InPort" eOpposite="#//InPort/connectedToOut"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Asset" abstract="true" eSuperTypes="#//Item">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="surfaceArea" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="purchaseCosts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationalCosts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commissioningDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expectedDecommissioningDate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="installationCosts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="marginalCosts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="owner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contour" upperBound="-1"
        eType="#//Contour" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" upperBound="-1"
        eType="#//Location" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="area" eType="#//Area" eOpposite="#//Area/asset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containingBuilding" eType="#//AbstractBuilding"
        eOpposite="#//AbstractBuilding/asset"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericConsumer" eSuperTypes="#//Consumer"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenericProducer" eSuperTypes="#//Producer"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenericStorage" eSuperTypes="#//Storage"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenericTransport" eSuperTypes="#//Transport"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenericConversion" eSuperTypes="#//Conversion"/>
  <eClassifiers xsi:type="ecore:EClass" name="AggregatedTransport" eSuperTypes="#//Transport">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregationOf" upperBound="-1"
        eType="#//Transport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregatedConversion" eSuperTypes="#//Conversion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregationOf" upperBound="-1"
        eType="#//Conversion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregatedStorage" eSuperTypes="#//Storage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregationOf" upperBound="-1"
        eType="#//Storage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BuildingTypeEnum">
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="RESIDENTIAL" value="1"/>
    <eLiterals name="GATHERING" value="2"/>
    <eLiterals name="PRISON" value="3"/>
    <eLiterals name="HEALTHCARE" value="4"/>
    <eLiterals name="INDUSTRY" value="5"/>
    <eLiterals name="OFFICE" value="6"/>
    <eLiterals name="EDUCATION" value="7"/>
    <eLiterals name="SPORTS" value="8"/>
    <eLiterals name="SHOPPING" value="9"/>
    <eLiterals name="GREENHOUSE" value="10"/>
    <eLiterals name="OTHER" value="11"/>
    <eLiterals name="UTILITY" value="12"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Building" eSuperTypes="#//AbstractBuilding">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roofArea" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wallArea" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="windowArea" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="perimeter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roofType" eType="#//RoofTypeEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buildingUnits" upperBound="-1"
        eType="#//BuildingUnit" containment="true" eOpposite="#//BuildingUnit/building"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConsTypeEnum">
    <eLiterals name="PRIMARY"/>
    <eLiterals name="FINAL" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProdTypeEnum">
    <eLiterals name="RENEWABLE"/>
    <eLiterals name="NONRENEWABLE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HeatStorage" eSuperTypes="#//Storage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="heatLoss" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minStorageTemperature"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxStorageTemperature"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GasHeater" eSuperTypes="#//Conversion"/>
  <eClassifiers xsi:type="ecore:EClass" name="HeatNetwork" eSuperTypes="#//Transport"/>
  <eClassifiers xsi:type="ecore:EClass" name="GasNetwork" eSuperTypes="#//Transport"/>
  <eClassifiers xsi:type="ecore:EClass" name="Insulation" eSuperTypes="#//Asset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="thermalInsulation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SinkProducer" eSuperTypes="#//Producer"/>
  <eClassifiers xsi:type="ecore:EClass" name="SinkConsumer" eSuperTypes="#//Consumer"/>
  <eClassifiers xsi:type="ecore:EClass" name="HeatPipe" eSuperTypes="#//Transport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diameter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutHPort" eSuperTypes="#//OutPort">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minTemperature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxTemperature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temperature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InHPort" eSuperTypes="#//InPort">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minTemperature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxTemperature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temperature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutEPort" eSuperTypes="#//OutPort">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minVoltage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxVoltage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="voltage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InEPort" eSuperTypes="#//InPort">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minVoltage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxVoltage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="voltage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutGPort" eSuperTypes="#//OutPort">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxPressure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minPressure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pressure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InGPort" eSuperTypes="#//InPort">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxPressure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minPressure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pressure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeothermalSource" eSuperTypes="#//Producer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wellDepth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CHP" eSuperTypes="#//Conversion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxEfficiencyHeat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxEfficiencyElectricity"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HeatPump" eSuperTypes="#//Conversion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="#//SourceTypeEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SourceTypeEnum">
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="AIR" value="1"/>
    <eLiterals name="SUB_SURFACE" value="2"/>
    <eLiterals name="AQUIFER" value="3"/>
    <eLiterals name="SURFACE_WATER" value="4"/>
    <eLiterals name="HEAT_NETWORK" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AggrTypeEnum">
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="NOT_AGGREGATED" value="1"/>
    <eLiterals name="PER_COMMODITY" value="2"/>
    <eLiterals name="TOTAL_ENERGY" value="3"/>
    <eLiterals name="TOTAL_CAPABILITY" value="4"/>
    <eLiterals name="PER_CAPIBILITY" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AreaTypeEnum">
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="ROAD" value="1"/>
    <eLiterals name="RAILWAY" value="2"/>
    <eLiterals name="TERRAIN" value="3"/>
    <eLiterals name="RURAL_AREA" value="4"/>
    <eLiterals name="BUILT" value="5"/>
    <eLiterals name="WATER" value="6"/>
    <eLiterals name="SEA" value="7"/>
    <eLiterals name="RIVER" value="8"/>
    <eLiterals name="CANAL" value="9"/>
    <eLiterals name="LAKE" value="10"/>
    <eLiterals name="LAND" value="11"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HeatDemand" eSuperTypes="#//Consumer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//HeatDemandTypeEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HeatDemandTypeEnum">
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="SPACE_HEATING" value="1"/>
    <eLiterals name="HOT_TAPWATER" value="2"/>
    <eLiterals name="SH_AND_HTW" value="3"/>
    <eLiterals name="OTHER" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElectricityDemand" eSuperTypes="#//Consumer"/>
  <eClassifiers xsi:type="ecore:EClass" name="GasDemand" eSuperTypes="#//Consumer"/>
  <eClassifiers xsi:type="ecore:EClass" name="GeothermalPotential" eSuperTypes="#//Potential">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temperature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="depth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contour">
    <eStructuralFeatures xsi:type="ecore:EReference" name="point" lowerBound="3" upperBound="-1"
        eType="#//Location" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HousingTypeEnum">
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="OWNER_OCCUPIED_PROPERTY" value="1"/>
    <eLiterals name="PRIVATE_RENTAL" value="2"/>
    <eLiterals name="HOUSING_ASSOCIATION" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EconomicProperties">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="averageIncome" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="averageWOZvalue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentageOwnerOccupiedProperties"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentageHousingAssociation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentagePrivateRental"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SocialProperties">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="socialCohesion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="populationDensity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfInhabitants" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegalArea" eSuperTypes="#//Potential">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="purpose" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RoofTypeEnum">
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="FLATROOF" value="1"/>
    <eLiterals name="SLANTEDROOF" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnergyLabelEnum">
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="LABEL_G" value="1"/>
    <eLiterals name="LABEL_F" value="2"/>
    <eLiterals name="LABEL_E" value="3"/>
    <eLiterals name="LABEL_D" value="4"/>
    <eLiterals name="LABEL_C" value="5"/>
    <eLiterals name="LABEL_B" value="6"/>
    <eLiterals name="LABEL_A" value="7"/>
    <eLiterals name="LABEL_AP" value="8"/>
    <eLiterals name="LABEL_APP" value="9"/>
    <eLiterals name="LABEL_APPP" value="10"/>
    <eLiterals name="LABEL_APPPP" value="11"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnergyService" abstract="true" eSuperTypes="#//Service"/>
  <eClassifiers xsi:type="ecore:EClass" name="DemandResponseService" eSuperTypes="#//EnergyService"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transformer" eSuperTypes="#//Transport"/>
  <eClassifiers xsi:type="ecore:EClass" name="HeatExchange" eSuperTypes="#//Transport"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ResidentialBuildingTypeEnum">
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="VRIJSTAANDE_WONING" value="1"/>
    <eLiterals name="RIJTJESHUIS" value="2"/>
    <eLiterals name="HOEKWONING" value="3"/>
    <eLiterals name="APPARTEMENT" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Measures">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//Item" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EConnection" eSuperTypes="#//Transport"/>
  <eClassifiers xsi:type="ecore:EClass" name="HConnection" eSuperTypes="#//Transport"/>
  <eClassifiers xsi:type="ecore:EClass" name="GConnection" eSuperTypes="#//Transport"/>
  <eClassifiers xsi:type="ecore:EClass" name="PowerPlant" eSuperTypes="#//Producer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fuel" eType="#//PowerPlantFuelEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLoad" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minLoad" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effMaxLoad" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effMinLoad" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="energyCarrier" eType="#//EnergyCarrier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PowerPlantFuelEnum">
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="COAL" value="1"/>
    <eLiterals name="BLAST_FURNACE_GAS" value="2"/>
    <eLiterals name="NATURAL_GAS" value="3"/>
    <eLiterals name="URANIUM" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" abstract="true" eSuperTypes="#//Item"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractBuilding" abstract="true" eSuperTypes="#//Asset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="energyLabel" eType="#//EnergyLabelEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asset" upperBound="-1"
        eType="#//Asset" containment="true" eOpposite="#//Asset/containingBuilding"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="detailLevel" eType="#//AreaScopeEnum"
        defaultValueLiteral="UNDEFINED"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggrType" eType="#//AggrTypeEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="area" eType="#//Area" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service" abstract="true" eSuperTypes="#//Item"/>
  <eClassifiers xsi:type="ecore:EClass" name="AggregatorService" eSuperTypes="#//EnergyService"/>
  <eClassifiers xsi:type="ecore:EClass" name="EVChargingStation" eSuperTypes="#//Consumer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Potential" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contour" eType="#//Contour"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="areas" upperBound="-1"
        eType="#//Area" eOpposite="#//Area/potentials"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WindPotential" eSuperTypes="#//Potential">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="windspeed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregatedBuilding" eSuperTypes="#//AbstractBuilding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregationOf" upperBound="-1"
        eType="#//AbstractBuilding"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfBuildings" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SectorEnum">
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="GEBOUWDE_OMGEVING" value="1"/>
    <eLiterals name="ZAKELIJKE_DIENSTVERLENING" value="2"/>
    <eLiterals name="INDUSTRIE" value="3"/>
    <eLiterals name="AGRO_TUINBOUW" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Potentials">
    <eStructuralFeatures xsi:type="ecore:EReference" name="potential" upperBound="-1"
        eType="#//Potential" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnergyCarrier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="energyContentPerUnit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emissionPerUnit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="energyCarrierType" eType="#//EnergyCarrierTypeEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateOfMatter" eType="#//StateOfMatterEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Losses" eSuperTypes="#//Consumer"/>
  <eClassifiers xsi:type="ecore:EClass" name="PowerToX" eSuperTypes="#//Conversion"/>
  <eClassifiers xsi:type="ecore:EClass" name="CCS" eSuperTypes="#//Storage"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EnergyCarrierTypeEnum">
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="RENEWABLE" value="1"/>
    <eLiterals name="FOSSIL" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StateOfMatterEnum">
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="SOLID" value="1"/>
    <eLiterals name="LIQUID" value="2"/>
    <eLiterals name="GASEOUS" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AvailableEnergyCarriers">
    <eStructuralFeatures xsi:type="ecore:EReference" name="energyCarrier" upperBound="-1"
        eType="#//EnergyCarrier" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuelCell" eSuperTypes="#//Conversion"/>
  <eClassifiers xsi:type="ecore:EClass" name="XToPower" eSuperTypes="#//Conversion"/>
  <eClassifiers xsi:type="ecore:EClass" name="WindParc" eSuperTypes="#//WindTurbine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfTurbines" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PVParc" eSuperTypes="#//PVPanel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfPanels" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnergySystemInformation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="availableEnergyCarriers"
        eType="#//AvailableEnergyCarriers" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="energyPrices" eType="#//EnergyPrices"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pump" eSuperTypes="#//Transport"/>
  <eClassifiers xsi:type="ecore:EClass" name="Valve" eSuperTypes="#//Transport"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnergyPrices">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elecPrice" eType="#//GenericProfile"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gasPrice" eType="#//GenericProfile"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericProfile" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="profileType" eType="#//ProfileTypeEnum"
        defaultValueLiteral="UNDEFINED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticProfile" abstract="true" eSuperTypes="#//GenericProfile"/>
  <eClassifiers xsi:type="ecore:EClass" name="DateTimeProfile" eSuperTypes="#//StaticProfile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pitem" upperBound="-1"
        eType="#//PItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartEndProfile" eSuperTypes="#//StaticProfile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="item" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartDurationProfile" eSuperTypes="#//StaticProfile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duration" lowerBound="1"
        eType="#//Duration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="item" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalProfile" abstract="true" eSuperTypes="#//GenericProfile"/>
  <eClassifiers xsi:type="ecore:EClass" name="MultiplierProfile" eSuperTypes="#//GenericProfile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="staticprofile" lowerBound="1"
        eType="#//StaticProfile" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="#//StaticProfile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
</ecore:EPackage>
